/**
 * PROTOTYPE — second Neat editor export ("try this one"). Pastel stops this
 * time, close to Align's own wash. Keys the installed 1.0.2 does not declare
 * were dropped (14: secondaryWaveEnabled, secondaryWaveFrequencyX, secondaryWaveFrequencyY, secondaryWaveAmplitude, secondaryWaveSpeed, secondaryWaveAngle, textureMode, bakeEdgeSoftness, prismEdgeEnabled, prismEdgeIntensity, prismEdgeThinness, prismEdgeSpread, prismEdgeSpeed, prismEdgeRipple).
 *
 * Note `wireframe: true` is set in the export — that draws the mesh as lines
 * over `backgroundColor`, which is a different look from a filled field.
 */
import type { NeatConfig } from "@firecms/neat";

export const NEAT_CONFIG: NeatConfig = {
  colors: [
    { color: "#cdb4db", enabled: true }, // thistle
    { color: "#ffc8dd", enabled: true }, // pastel petal
    { color: "#ffafcc", enabled: true }, // baby pink
    { color: "#bde0fe", enabled: true }, // icy blue
    { color: "#a2d2ff", enabled: true }, // sky blue
  ],
  speed: 4.5,
  horizontalPressure: 6,
  verticalPressure: 6,
  waveFrequencyX: 3,
  waveFrequencyY: 3,
  waveAmplitude: 3,
  shadows: 2,
  highlights: 3,
  colorBrightness: 1,
  colorSaturation: -4,
  wireframe: true,
  antialias: false,
  colorBlending: 6,
  backgroundColor: "#ffc8dd",
  backgroundAlpha: 1,
  grainScale: 0,
  grainSparsity: 0,
  grainIntensity: 0,
  grainSpeed: 0,
  resolution: 0.4,
  yOffset: 3956,
  yOffsetWaveMultiplier: 10.9,
  yOffsetColorMultiplier: 3.8,
  yOffsetFlowMultiplier: 6.2,
  flowDistortionA: 2.8,
  flowDistortionB: 2.4,
  flowScale: 1.5,
  flowEase: 0.41,
  flowEnabled: false,
  enableProceduralTexture: false,
  transparentTextureVoid: false,
  textureVoidLikelihood: 0.06,
  textureVoidWidthMin: 10,
  textureVoidWidthMax: 500,
  textureBandDensity: 0.8,
  textureColorBlending: 0.06,
  textureSeed: 333,
  textureEase: 0.72,
  proceduralBackgroundColor: "#FFED00",
  textureShapeTriangles: 20,
  textureShapeCircles: 15,
  textureShapeBars: 15,
  textureShapeSquiggles: 10,
  domainWarpEnabled: false,
  domainWarpIntensity: 0,
  domainWarpScale: 3,
  vignetteIntensity: 0.3,
  vignetteRadius: 0.6,
  fresnelEnabled: true,
  fresnelPower: 2,
  fresnelIntensity: 0.2,
  fresnelColor: "#FF0000",
  iridescenceEnabled: false,
  iridescenceIntensity: 0.8,
  iridescenceSpeed: 1,
  bloomIntensity: 0.4,
  bloomThreshold: 0.7,
  chromaticAberration: 9,
  shapeType: "plane",
  shapeRotationX: 0,
  shapeRotationY: 0,
  shapeRotationZ: 0,
  shapeAutoRotateSpeedX: 0,
  shapeAutoRotateSpeedY: 0,
  sphereRadius: 15,
  torusRadius: 15,
  torusTube: 5,
  cylinderRadius: 10,
  cylinderHeight: 40,
  planeBend: 0,
  planeTwist: 0,
  silhouetteFade: 0.25,
  cylinderFade: 0.08,
  ribbonFade: 0.05,
  flatShading: true,
  cameraLock: true,
  cameraX: 0,
  cameraY: 0,
  cameraZ: 0,
  cameraRotationX: 0,
  cameraRotationY: 0,
  cameraRotationZ: 0,
  cameraZoom: 1,
};
